#Requires -Version 5.1
<#
.SYNOPSIS
    PRAE Auto Recheck Scheduler
    Registers Windows Scheduled Tasks that periodically re-collect evidence,
    re-evaluate the truth registry, and update missing-partial records.
    No production mutation. Read-only evidence collection only.

    governance_mode=LOCKED  production_mutation=NONE  auto_repair=DISABLED
.DESCRIPTION
    Registers two tasks per project:
      BossMind-PRAE-EvidenceRecheck-<project>-Hourly   (every 60 min)
      BossMind-PRAE-EvidenceRecheck-<project>-Daily    (every 24 h, at 03:00)

    Each task runs:
      PRAE-RunEvidenceRecheck.ps1 -ProjectName <name>

    PRAE-RunEvidenceRecheck.ps1 is a thin orchestrator that calls:
      EvidenceCollector -> MemoryPromotionGate -> TruthRegistry -> MissingPartialResolver

.PARAMETER Action
    Register | Unregister | Status
.PARAMETER ProjectName
    e.g. "bossmind-resumora"
.PARAMETER ProjectRoot
    e.g. "D:\BossMind\bossmind-resumora"
.PARAMETER PRAERoot
    Default: D:\BossMind\bossmind-shared\prae
.PARAMETER HourlyIntervalMinutes
    Default: 60
.PARAMETER DailyHour
    Hour (0-23) for daily deep recheck. Default: 3
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateSet("Register","Unregister","Status")]
    [string]$Action,

    [Parameter(Mandatory)]
    [string]$ProjectName,

    [string]$ProjectRoot = "",

    [string]$PRAERoot            = "D:\BossMind\bossmind-shared\prae",
    [int]   $HourlyIntervalMinutes = 60,
    [int]   $DailyHour             = 3
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Set-Variable -Name GOV_MODE    -Value "LOCKED"  -Option ReadOnly -Force
Set-Variable -Name GOV_MUTATION -Value "NONE"   -Option ReadOnly -Force

$safeName      = $ProjectName.ToLower().Replace(' ','-').Replace('/','-')
$taskFolder    = "\BossMind\PRAE\EvidenceRecheck"
$taskHourly    = "BossMind-PRAE-EvidenceRecheck-$safeName-Hourly"
$taskDaily     = "BossMind-PRAE-EvidenceRecheck-$safeName-Daily"
$orchScript    = Join-Path $PRAERoot "PRAE-RunEvidenceRecheck.ps1"
$psExe         = "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe"
$currentUser   = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name

function Write-Sch  { param([string]$T) Write-Host "  [SCHED] $T" -ForegroundColor Cyan  }
function Write-Pass { param([string]$T) Write-Host "  [PASS ] $T" -ForegroundColor Green }
function Write-Fail { param([string]$T) Write-Host "  [FAIL ] $T" -ForegroundColor Red   }
function Write-Info { param([string]$T) Write-Host "  [INFO ] $T" -ForegroundColor Gray  }

Write-Host ""
Write-Host "  +--------------------------------------------------+" -ForegroundColor DarkCyan
Write-Host "  |  PRAE Auto Recheck Scheduler                     |" -ForegroundColor Cyan
Write-Host "  |  Project : $($ProjectName.PadRight(38))|" -ForegroundColor DarkCyan
Write-Host "  |  Action  : $($Action.PadRight(38))|" -ForegroundColor DarkCyan
Write-Host "  +--------------------------------------------------+" -ForegroundColor DarkCyan
Write-Host ""

# -- STATUS ----------------------------------------------------
if ($Action -eq "Status") {
    foreach ($taskName in @($taskHourly, $taskDaily)) {
        $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
        if ($task) {
            $state = $task.State.ToString()
            Write-Pass "$taskName : $state"
            $lastRun = (Get-ScheduledTaskInfo -TaskName $taskName -ErrorAction SilentlyContinue)?.LastRunTime
            if ($lastRun -and $lastRun -gt [datetime]"2000-01-01") {
                Write-Info "  Last run: $lastRun"
            }
        } else {
            Write-Info "$taskName : NOT REGISTERED"
        }
    }
    Write-Host ""
    return
}

# -- UNREGISTER ------------------------------------------------
if ($Action -eq "Unregister") {
    foreach ($taskName in @($taskHourly, $taskDaily)) {
        $task = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
        if ($task) {
            Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
            Write-Pass "Removed: $taskName"
        } else {
            Write-Info "Not found (already absent): $taskName"
        }
    }
    Write-Host ""
    return
}

# -- REGISTER --------------------------------------------------
# Build the orchestrator script if it doesn't exist
if (-not (Test-Path $orchScript)) {
    Write-Info "Creating orchestrator script: $orchScript"
    $orchContent = @"
#Requires -Version 5.1
<#
.SYNOPSIS
    PRAE Evidence Recheck Orchestrator
    Called by scheduled tasks. Runs full evidence collection + promotion + resolver.
    Auto-generated by PRAE-AutoRecheckScheduler.ps1
#>
param(
    [Parameter(Mandatory)]
    [string]`$ProjectName,
    [string]`$ProjectRoot = "",
    [string]`$PRAERoot    = "D:\BossMind\bossmind-shared\prae"
)

Set-StrictMode -Version Latest
`$ErrorActionPreference = "Stop"

Set-Variable -Name GOV_MODE    -Value "LOCKED"  -Option ReadOnly -Force
Set-Variable -Name GOV_MUTATION -Value "NONE"   -Option ReadOnly -Force

`$knownRoots = @{
    "bossmind-resumora"           = "D:\BossMind\bossmind-resumora"
    "bossmind-elegancyart"        = "D:\BossMind\bossmind-elegancyart"
    "bossmind-ai-video-generator" = "D:\BossMind\bossmind-ai-video-generator"
    "bossmind-global-stock"       = "D:\BossMind\bossmind-global-stock"
    "bossmind-master-admin"       = "D:\BossMind\bossmind-master-admin"
}

if (-not `$ProjectRoot -and `$knownRoots.ContainsKey(`$ProjectName)) {
    `$ProjectRoot = `$knownRoots[`$ProjectName]
}
if (-not `$ProjectRoot) {
    Write-Warning "PRAE-RunEvidenceRecheck: No ProjectRoot for `$ProjectName"
    exit 1
}

`$collector    = Join-Path `$PRAERoot "PRAE-EvidenceCollector.ps1"
`$gate         = Join-Path `$PRAERoot "PRAE-MemoryPromotionGate.ps1"
`$registry     = Join-Path `$PRAERoot "PRAE-TruthRegistry.ps1"
`$resolver     = Join-Path `$PRAERoot "PRAE-MissingPartialResolver.ps1"

if (-not (Test-Path `$collector) -or -not (Test-Path `$gate)) {
    Write-Warning "PRAE-RunEvidenceRecheck: Required scripts not found in `$PRAERoot"
    exit 1
}

Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

# 1. Collect evidence
`$evidence = & `$collector -ProjectName `$ProjectName -ProjectRoot `$ProjectRoot -PRAERoot `$PRAERoot

# 2. Evaluate and promote
`$record = & `$gate -Evidence `$evidence -ProjectName `$ProjectName ``
    -WriteToRegistry ``
    -TruthRegistryScript `$registry

# 3. Resolve missing/partial
if (Test-Path `$resolver) {
    & `$resolver -ProjectName `$ProjectName -TruthRegistryScript `$registry
}

Write-Verbose "PRAE-RunEvidenceRecheck: Complete for `$ProjectName -> `$(`$record.overall_confidence)"
"@
    $dir = Split-Path $orchScript -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    [System.IO.File]::WriteAllText($orchScript, $orchContent, [System.Text.Encoding]::UTF8)
    Write-Pass "Orchestrator created: $orchScript"
}

# Shared task components
$rootArg  = if ($ProjectRoot) { " -ProjectRoot `"$ProjectRoot`"" } else { "" }
$taskArgs = "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$orchScript`" -ProjectName `"$ProjectName`"$rootArg -PRAERoot `"$PRAERoot`""

$action_obj = New-ScheduledTaskAction -Execute $psExe -Argument $taskArgs

$settings = New-ScheduledTaskSettingsSet `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10) `
    -MultipleInstances  IgnoreNew `
    -StartWhenAvailable `
    -DontStopIfGoingOnBatteries `
    -AllowStartIfOnBatteries

$principal = New-ScheduledTaskPrincipal `
    -UserId    $currentUser `
    -LogonType Interactive `
    -RunLevel  Highest

# -- Hourly task -----------------------------------------------
$trigHourly = New-ScheduledTaskTrigger `
    -RepetitionInterval (New-TimeSpan -Minutes $HourlyIntervalMinutes) `
    -Once -At (Get-Date)

$existH = Get-ScheduledTask -TaskName $taskHourly -ErrorAction SilentlyContinue
if ($existH) { Unregister-ScheduledTask -TaskName $taskHourly -Confirm:$false }

Register-ScheduledTask `
    -TaskName    $taskHourly `
    -TaskPath    $taskFolder `
    -Action      $action_obj `
    -Trigger     $trigHourly `
    -Settings    $settings `
    -Principal   $principal `
    -Description "PRAE hourly evidence recheck for $ProjectName. governance_mode=LOCKED production_mutation=NONE" `
    -Force | Out-Null

$verH = Get-ScheduledTask -TaskName $taskHourly -ErrorAction SilentlyContinue
if ($verH) {
    Write-Pass "Hourly task registered: $taskFolder\$taskHourly (every ${HourlyIntervalMinutes}min)"
} else {
    Write-Fail "Hourly task failed to register"
}

# -- Daily task ------------------------------------------------
$dailyTime  = (Get-Date).Date.AddHours($DailyHour)
if ($dailyTime -le (Get-Date)) { $dailyTime = $dailyTime.AddDays(1) }
$trigDaily  = New-ScheduledTaskTrigger -Daily -At $dailyTime

$existD = Get-ScheduledTask -TaskName $taskDaily -ErrorAction SilentlyContinue
if ($existD) { Unregister-ScheduledTask -TaskName $taskDaily -Confirm:$false }

Register-ScheduledTask `
    -TaskName    $taskDaily `
    -TaskPath    $taskFolder `
    -Action      $action_obj `
    -Trigger     $trigDaily `
    -Settings    $settings `
    -Principal   $principal `
    -Description "PRAE daily evidence recheck for $ProjectName at $DailyHour:00. governance_mode=LOCKED production_mutation=NONE" `
    -Force | Out-Null

$verD = Get-ScheduledTask -TaskName $taskDaily -ErrorAction SilentlyContinue
if ($verD) {
    Write-Pass "Daily task registered: $taskFolder\$taskDaily (daily at $DailyHour:00)"
} else {
    Write-Fail "Daily task failed to register"
}

Write-Host ""
Write-Info "governance_mode=$GOV_MODE  production_mutation=$GOV_MUTATION"
Write-Host ""
Write-Sch "Run now to force immediate recheck:"
Write-Host "  & '$orchScript' -ProjectName '$ProjectName'" -ForegroundColor White
Write-Host ""
